
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build" , "-t","$_AR_HOSTNAME/$PROJECT_ID/b2proj1/$_SERVICE_NAME:$_SERVER", ".", "-f","Dockerfile", "--cache-from", "$_AR_HOSTNAME/$PROJECT_ID/b2proj1/$_SERVICE_NAME:$_SERVER"]


images:
  - >-
    "$_AR_HOSTNAME/$PROJECT_ID/b2proj1/$_SERVICE_NAME:$_SERVER"
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY