
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build" , "-t","$_AR_HOSTNAME/$_PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$_SERVER", ".", "-f","Dockerfile", "--cache-from", "$_AR_HOSTNAME/$_PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$_SERVER"]


images:
  - "$_AR_HOSTNAME/$_PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$_SERVER"
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY