name: Code check


on:
    push:
      branches:
        - stg

  
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'  # Adjust to your Python version
            
            - name: Install pipenv
              run:  pip install pipenv

            - name: Install dev libs
              run: pipenv install --dev --python $(which python)

            - name: Run Black for code formatting 
              run: pipenv run black .
            
            - name: Run import sorting
              run: pipenv run isort .
              
            - name: Code quality check
              run: pipenv run pylint --fail-under=8 --disable=line-too-long,invalid-name $(git ls-files '*.py')

            - name: Build Docker Image
              run: docker build -t test_run .

            - name: Run Unit Test
              run: docker run --rm test_run pytest

